# Generated by Django 5.1.1 on 2024-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[("proj", "Project"), ("task", "Task")],
                default="task",
                max_length=4,
            ),
        ),
    ]
