# Generated by Django 5.1.1 on 2024-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invitation_duration_invitation_time_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
