# Generated by Django 5.1.1 on 2024-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_active_project_difficulty_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='time_start',
            new_name='beginTime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='time_completed',
            new_name='completeTime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='difficulty_level',
            new_name='difficultyLevel',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='time_end',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='time_init',
            new_name='initTime',
        ),
        migrations.AlterField(
            model_name='project',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
