# Generated by Django 5.1.1 on 2024-11-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_time_start_project_begintime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='difficultyLevel',
            new_name='diffLevel',
        ),
    ]
