# Generated by Django 5.1.1 on 2024-11-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_difficultylevel_project_difflevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='time_send',
            new_name='sendTime',
        ),
    ]
