# Generated by Django 5.1.1 on 2024-11-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_inittime_project_initime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='iniTime',
            new_name='initTime',
        ),
    ]
