# Generated by Django 5.1.1 on 2024-11-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_initime_project_inittime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='context',
            new_name='content',
        ),
    ]
