# Generated by Django 5.1.1 on 2024-11-02 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_context_invitation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
