# Generated by Django 5.1.1 on 2024-11-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='canFinish',
            field=models.BooleanField(default=False),
        ),
    ]
