# Generated by Django 5.1.1 on 2024-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_permissions_canaddmember_permissions_canremovemember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
